apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
    containers:
      - name: python
        image: gcr.io/mahmoud-ibrahim-2-project/python-app
        ports:
        - containerPort: 80